In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('customer.csv')

In [9]:
df.sample(5)

    age  gender   review education purchased
8    65  Female  Average        UG        No
33   89  Female     Good        PG       Yes
40   39    Male     Good    School        No
13   57  Female  Average    School        No
45   61    Male     Poor        PG       Yes

In [10]:
df = df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [15]:
x_train

     review education
9      Good        UG
8   Average        UG
35     Poor    School
29  Average        UG
38     Good    School
2      Good        PG
47     Good        PG
26     Poor        PG
4   Average        UG
28     Poor    School
46     Poor        PG
39     Poor        PG
42     Good        PG
6      Good    School
11     Good        UG
14     Poor        PG
1      Poor        UG
32  Average        UG
27     Poor        PG
45     Poor        PG
36     Good        UG
10     Good        UG
40     Good    School
15     Poor        UG
17     Poor        UG
20  Average    School
48     Good        UG
18     Good    School
23     Good    School
13  Average    School
34  Average    School
43     Poor        PG
21  Average        PG
16     Poor        UG
30  Average        UG
24  Average        PG
49     Good        UG
22     Poor        PG
3      Good        PG
12     Poor    School

In [18]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [19]:
oe.fit(X_train)

ValueError: Found unknown categories ['medium', 'high', 'low'] in column 0 during fit

In [20]:
X_train = oe.transform(X_train)
X_train

AttributeError: 'OrdinalEncoder' object has no attribute '_missing_indices'

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [22]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [23]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_train

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0])